site_name: SDFusion Blender Addon Documentation
site_url: https://sdfusion-blender-addon.readthedocs.io/

nav:
  - Home: index.md
  - Installation: installation.md  # これでOK
  - How to Use: how_to_use.md
  - Gallery: gallery.md
  #- Movies: movies.md